name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule init
    - name: Update submodules
      run: git submodule update
    - name: configure
      run: cmake .
    - name: make doc
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'doc'
    - name: Build and Deploy GH Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
