name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Extract submodules
      run: git submodule init
      run: git submodule update
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: make doc
      run: make doc
